# Generated by Django 3.2.8 on 2021-10-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_auto_20211020_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inmatch',
            field=models.CharField(blank=True, default=1, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, default='batsman', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position_order',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
