# Generated by Django 3.2.8 on 2021-10-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20211026_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='inmatch',
        ),
        migrations.AddField(
            model_name='player',
            name='inmatch',
            field=models.ManyToManyField(blank=True, default=1, to='structure.match'),
        ),
    ]
