# Generated by Django 3.2.8 on 2021-10-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20211026_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inmatch',
            field=models.ManyToManyField(blank=True, related_name='inmatch', to='structure.match'),
        ),
    ]
