# Generated by Django 3.2.8 on 2021-10-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_player_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', upload_to='product_pictures'),
        ),
    ]
